tools/check-codingrules.sh
tools/codingrules-uncrustify-riot.cfg

* Script based on uncrustify tools.
* Use the same uncrustify configuration as RIOT-OS.
Signed-off-by: Stephen Clymans <stephen@clymans.fr>

tools : Add script to check coding rules for .c and .h files.

---

boards/cogip2019-cortex/Makefile.include
platforms/cogip2019-cortex/Makefile
tools/fwsize.sh

This display graphbar based on available Flash & RAM in the MCU
and after checking GNU size outputs of a freshly built firmware.
Signed-off-by: Yannick Gicquel <ygicquel@gmail.com>

tools: add script to display MCU firmware footprint

---

boards/cogip2019-cortex-native/vl53l0x.c
platforms/cortex/include/platform.h
platforms/cortex/platform.c
robotics/avoidance.c

Use a shared memory array containing sensors values provided by the simulator.
Also add pose order info in output of "_pose" shell command.

Add communication between simulator and native firmware

---

controllers/ctrl.c
controllers/include/ctrl.h
controllers/quadpid/quadpid.c
platforms/cortex/include/platform.h
platforms/cortex/platform.c

Rename "_pose" shell command into "_state" as it prints more than positions.
Add cycle and speed info to "_state" command output.
Fix uint32_t printf format specifier.

Rename and improve shell command to get robot state

---

.github/workflows/compilation.yml

Fix 404 errors from `apt-get install`
Tested 5 times, worked 5 times, seems ok.

Fix fetch workflow

---

Makefile.dep
Makefile.include
examples/shell_menu/Makefile
examples/shell_menu/main.c
sys/Makefile
sys/Makefile.dep
sys/include/shell_menu.h
sys/shell_menu/Makefile
sys/shell_menu/shell_menu.c

Add a sys directory in mcu-firmware.
Add a first module shell_menu.
This module extends the shell module by providing an API
to declare sub-menus and navigate through them.
Also add an example directory to add example of modules usage.

Add shell_menu module

---

drivers/lds01/include/lds01.h
drivers/lds01/include/lds01_params.h
drivers/lds01/lds01.c
drivers/lds01_dma/Makefile
drivers/lds01_dma/Makefile.dep
drivers/lds01_dma/include/lds01.h
drivers/lds01_dma/include/lds01_params.h
drivers/lds01_dma/lds01.c
drivers/lds01_dma/lds01_native.c
examples/lds01/include/lds01_params.h
examples/lds01_dma/include/lds01_params.h
examples/lds01_dma/include/shmem_params.h
examples/lds01_dma/main.c

Support native compilation of lds01_dma driver.
Data can be updated using shared memory is configured.
Add the possibility to invert distance and intensity data.
Add configuration of the minimum intensity required to validate a distance.

LDS01 DMA Driver: Add native support

---

applications/app_test/path.c
applications/cup2019/path.c
lib/path/include/path.h
lib/path/path.c
planners/astar/planner.c
planners/shell_planners/shell_planners.c
platforms/cortex/platform.c

Define Path as a module and cleanup unused functions
tested in simulation for both _cup2019_ and _app_test_ targets.

Path as module

---

examples/lds01/main.c
examples/lds01_dma/main.c

Add a command to set the intensity threshold.
Under this threshold, distances are considered invalid.

Add intensity_threshold command in examples lds01/lds01_dma 

---

sys/shell_menu/include/shell_menu/Command.hpp
sys/uartpb/include/uartpb/uartpb.hpp

Increase size of shell commands and Profobuf serialization buffer to fix segfault with pf_test and cortex platforms.

Fix buffer sizes for Protobuf

---

.github/workflows/compilation.yml
.gitignore
pkg/embedded-proto/Makefile

Create a stamp file when *.protoc files are built to not rebuild
python and C bindings at each build, which could be long.
Also add some CI improvments to handle generated files

Ensure *.proto files are not always rebuilt

---

.gitignore
Makefile
README.md
riot-patches/0001-sys-newlib_syscalls_default-set-_init-and-_fini-as-w.patch

All patches available in patches/ directory will be applied on RIOT sources using quilt.
A patched stamp file is created for each patch applied.
In case of patch deletion, launch a make distclean first.
A first patch to add weak attribute to _init() and _fini() functions in preparation of using libstdc++ is also added.

Add RIOT patching mechanism

---

.github/workflows/compilation.yml
Makefile.include
applications/app_test/app_shell.cpp
applications/cup2022/app_shell.cpp
controllers/quadpid/shell_quadpid/shell_quadpid.cpp
drivers/sd21/shell_sd21/shell_sd21.cpp
examples/lidar_obstacles/lidar_obstacles.cpp
examples/lidar_obstacles/main.cpp
examples/shell_menu/main.cpp
examples/shmem/main.cpp
examples/uartpb/main.cpp
examples/uartpb/uartpb-client.py
planners/shell_planners/shell_planners.cpp
platforms/shell_platforms/shell_platforms.cpp
sys/shell_menu/Command.cpp
sys/shell_menu/Menu.cpp
sys/shell_menu/include/shell_menu/Command.hpp
sys/shell_menu/include/shell_menu/Menu.hpp
sys/shell_menu/include/shell_menu/shell_menu.hpp
sys/shell_menu/shell_menu.cpp
sys/shell_menu/shell_menu_private.hpp

Refactor code to only use strings and containers allocated at compile time.

sys: shell_menu: remove dynamic allocation

---

Makefile
Makefile.include
makefiles/riot-patches.mk.inc

If patches have never been applied and a specific application is built,
patches are not applied. For example:
$ make -C applications/app_test
This commit fix this by adding patch target as a dependency for all apps
in Makefile.include.
Signed-off-by: Gilles DOFFE <g.doffe@gmail.com>

makefiles: fix RIOT patches application on specific application build

---

boards/cogip-nucleo-f446re/include/board.h
platforms/pegasus/lidar_obstacles.cpp
platforms/pegasus/trace_utils.cpp
platforms/pf_test/lidar_obstacles.cpp
platforms/pf_test/trace_utils.cpp

This commit introduces no functional changes.
Other boards are using different pwm devices for each motor and
have one hardware driver per motor.
To reproduce this configuration for consistency with other boards and
allow this board to be used in applications, split the dual motor driver
into two single motor drivers.
PWM device is configured twice in the same way which is acceptable.
Signed-off-by: Gilles DOFFE <g.doffe@gmail.com>

boards: cogip-nucleo-f446re: split motor driver configuration

---

lib/wizard/Wizard.cpp

cogip::uartpb::message_handler_t was converted from std::function to
etl::delegate in https://github.com/cogip/mcu-firmware/issues/68,
but the registration of wizard message handler was not updated accordingly.

lib: wizard: fix message handler registration

---

Makefile.include
makefiles/version_check.mk.inc

The mallinfo2 structure and function were introduced in glibc 2.33. Thus check glibc version on native architecture to avoid undefined reference to mallinfo2.

makefiles: check glibc version before use of mallinfo2

---

Makefile.dep
Makefile.include

Feature, module and package depencies are listed in Makefile.include which is dirty and less readable.
Move them to Makefile.dep and include it in Makefile.include.

makefiles: introduce Makefile.dep

---

.github/workflows/compilation.yml
README.md
applications/cup2022/app.cpp
applications/cup2022/app_arm.cpp
applications/cup2022/app_arm.hpp
applications/cup2022/app_arm_shell.cpp
applications/cup2022/app_arm_shell.hpp
boards/cogip-board/include/board.h
boards/cogip-board/include/periph_conf.h
drivers/lx_servo/include/lx_servo.h
drivers/lx_servo/lx_writer.h
examples/driver_lx_servo/main.c
examples/driver_vacuum_pump/main.c
platforms/pegasus/LxServo.cpp
platforms/pegasus/Makefile.dep
platforms/pegasus/PB_Actuators.proto
platforms/pegasus/Pump.cpp
platforms/pegasus/include/Actuator.hpp
platforms/pegasus/include/LxServo.hpp
platforms/pegasus/include/Pump.hpp
platforms/pegasus/include/pf_actuators.hpp
platforms/pegasus/include/pf_pumps.hpp
platforms/pegasus/include/pf_servos.hpp
platforms/pegasus/include/vacuum_pump_params.h
platforms/pegasus/pf_actuators.cpp
platforms/pegasus/pf_pumps.cpp
platforms/pegasus/pf_servos.cpp
platforms/pegasus/platform.cpp
platforms/pegasus/trace_utils.cpp
platforms/pf_test/trace_utils.cpp

Add C++ classes to represent servomotors and vacuum pumps.
Initialize all actuators.
Define PB messages to send actuators state to Copilot.
Define PB messages to receive actuator commands from Copilot.
Create a thread to send actuators state.
Add uartpb handlers for actuator commands.

Add support for actuators and remote control using PB messages

---

makefiles/riot-patches.mk.inc

Using git command to get current branch will fail on detached head. Prefer simply using HEAD, working in all cases.

makefiles: riot-patches: use HEAD

---

lib/pid_ng/PB_Pid.proto
platforms/pegasus/motion_control.cpp

Instead of configuring PIDs using only one message for all, use a single message of each PID.
This is required to reduce PID Protobuf messages to fit into a CAN frame.

Split configuration of PIDs

---

motion_control/engines/platform_engine/Makefile.dep
motion_control/engines/platform_engine/PlatformEngine.cpp
motion_control/engines/platform_engine/include/platform_engine/PlatformEngine.hpp

Replace legacy callbacks by odometer and drive controller interfaces references.
This allows to use polymorphism in order to make platform engine work with any kind of odometer and drive controller type.
Add a new callback in order to dispatch pose reached state.

platform engine: replace callbacks by object references

---

motion_control/drive_controller/Makefile
motion_control/drive_controller/Makefile.include
motion_control/drive_controller/include/drive_controller/DifferentialDriveController.hpp
motion_control/drive_controller/include/drive_controller/DifferentialDriveControllerParameters.hpp
motion_control/drive_controller/include/drive_controller/DriveControllerInterface.hpp

The purpose of this interface is to define a common interface used by
platform engine in order to use any kind of drive controller (eg.
DifferentialDrive or HolonomicDrive)
The interface provides one method to set polar robot velocity.
COGIP robots are differential. So, implement the differential drive
controller in order to convert robot polar speed into speed ratio for
each motors.
The speed ratio is defined using the motor electrical information found
in the datasheet. This ratio reflect the percentage of nominal motor
voltage to apply in order to reach the velocity wanted.

177 motion control create new differentialdrive class

---

motion_control/controllers/passthrough_pose_pid_controller/PassthroughPosePIDController.cpp
motion_control/controllers/passthrough_pose_pid_controller/include/passthrough_pose_pid_controller/PassthroughPosePIDController.hpp

The DualPIDMetaController took 5 parameter, and the SpeedFilter took 5 inputs parameters. So, the PassthroughPosePIDController should input and output the same number of parameters in order to be inserted in the DualPID meta controller.

motion control: fix PassthroughPosePIDController parameters number

---

boards/cogip-native/Makefile.dep
boards/cogip-native/Makefile.features
platforms/pf-robot-motion-control/motion_control.cpp

Reproduce issue via interface (web or monitor):
* Select Back & Forth strategy
* Trigger a Next (wait or not for motion to complete)
* Press Reset
* Trigger another Next => robot no longer moves
Because if the target pose is identical to previous one, triggering a
check that skips motion when no change is detected leads to blocked
robot as it will never enable the motion control platform engine.

191 fix robot is not moving anymore after a reset on same strategy
